---
apiVersion: v1
kind: Service
metadata:
  name: config
  namespace: devel-services
spec:
  type: ClusterIP
  selector:
    app: config
  ports:
    - protocol: TCP
      port: 8102
      targetPort: 8102
