"Description" : "Deploy Services on ECS Cluster: Creates Target Group, Service and Task definition"

Parameters: 

  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
    Default: devel

  ServiceName:
    Description: The Name of the Service which we are going to deploy
    Type: String
    Default: test

  ImageUrl:
    Type: String
    Default: 596849958460.dkr.ecr.ap-south-1.amazonaws.com/config:devel-84
    Description: The url of a docker image that contains the application process that
                 will handle the traffic for this service

  VpcId:
    Description: The VPC ID
    Type: String
    Default: vpc-0236a53fffc25de35

  PrivateSubnetOne:
    Description: The First Private Subnet ID
    Type: String
    Default: subnet-098e65f35e91412c2
  PrivateSubnetTwo:
    Description: The Second Private Subnet ID
    Type: String
    Default: subnet-0548980c756958ec2
  PrivateSubnetThree:
    Description: The Third Private Subnet ID
    Type: String
    Default: subnet-0bb5218626088d807

  ECSTaskExecutionRole:
    Description: (Optional) An IAM role to give the service's containers if the code within needs to
                 access other AWS resources like S3 buckets, DynamoDB tables, etc
    Type: String
    Default: arn:aws:iam::596849958460:role/ecsTaskExecutionRole

  DesiredCount:
    Type: Number
    Default: 1
    Description: How many copies of the service task to run

  SecurityGroupECS:
    Type: String
    Default: sg-084429c164528a139
    Description: The Container Security Group

  LaunchType:
    Description: Please provide the LaunchType
    Type: String
    Default: FARGATE
    AllowedValues:
      - EC2
      - FARGATE

  ContainerCpu:
    Type: Number
    Default: 256
    Description: How much CPU to give the container. 1024 is 1 CPU
  ContainerMemory:
    Type: Number
    Default: 1024
    Description: How much memory in megabytes to give the container


  PublicIP:
    Description: Please provide IP connectivity option
    Type: String
    Default: ENABLED
    AllowedValues:
      - ENABLED
      - DISABLED
###########################################################################################
Resources:
###########################################################################################

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub ${EnvironmentName}-${ServiceName}-TG
      TargetType: ip
      HealthCheckIntervalSeconds: 60
      HealthCheckPath: /actuator
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 30
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 5
      Matcher:
        HttpCode: 200-499
      Port: 8102
      Protocol: HTTP
      VpcId: !Ref 'VpcId'

  ServiceNew: 
    Type: AWS::ECS::Service
    Properties: 
      LaunchType: !Ref LaunchType
      Cluster: !Sub ${EnvironmentName}-Cluster
      DesiredCount: !Ref DesiredCount
      TaskDefinition: !Ref 'TaskDefinitionNew'
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: !Ref PublicIP
          Subnets: [ !Ref 'PrivateSubnetOne' , !Ref 'PrivateSubnetTwo', !Ref 'PrivateSubnetThree' ]
          SecurityGroups: [!Ref 'SecurityGroupECS' ]

  TaskDefinitionNew:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub ${EnvironmentName}-Services
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !Ref ECSTaskExecutionRole
      TaskRoleArn: !Ref ECSTaskExecutionRole
      Cpu: !Ref ContainerCpu 
      Memory: !Ref ContainerMemory
      ContainerDefinitions:
        - Name: !Ref ServiceName
          Cpu: !Ref ContainerCpu
          Memory: !Ref ContainerMemory
          Image: !Ref ImageUrl

#################################################################################
  ServiceDiscoveryNameSpace:
    Type: AWS::ServiceDiscovery::PrivateDnsNamespace
    Properties:
      Description: "Service Discovery Namespace for Services" 
      Vpc: !Ref VpcId
      Name: !Sub ${EnvironmentName}-Services-Discovery

