---
apiVersion: v1
kind: Namespace
metadata:
  name: devel-services

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: config
  namespace: devel-services

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config 
  namespace: devel-services
  labels:
    app: config
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config
  template:
    metadata:
      labels:
        app: config
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      serviceAccountName: config
      containers:
      - name: config
        image: 596849958460.dkr.ecr.ap-south-1.amazonaws.com/config:devel-84
        ports:
        - name: config
          containerPort: 8102
        imagePullPolicy: IfNotPresent

      nodeSelector:
        kubernetes.io/os: linux
