{
 "title": "Load Balancing Stats",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "TargetResponseTime",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "production",
     "dimensions": { "LoadBalancer": "app/prodvpc/a2fa2fecdb6cd041" },
     "metricName": "TargetResponseTime",
     "namespace": "AWS/ApplicationELB",
     "region": "default",
     "statistics": [ "Average" ]
    },
    {
     "alias": "reports",
     "dimensions": { "LoadBalancer": "app/ellvpc/502ebe237ff21d6e" },
     "metricName": "TargetResponseTime",
     "namespace": "AWS/ApplicationELB",
     "region": "default",
     "statistics": [ "Average" ]
    },
    {
     "alias": "ecs-prod-cluster-external",
     "dimensions": {
      "LoadBalancer": "app/ecs-prod-cluster-external/25bc585d87b33ce5"
     },
     "metricName": "TargetResponseTime",
     "namespace": "AWS/ApplicationELB",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "HTTPCode_Target_4XX_Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "production",
     "dimensions": { "LoadBalancer": "app/prodvpc/a2fa2fecdb6cd041" },
     "metricName": "HTTPCode_Target_4XX_Count",
     "namespace": "AWS/ApplicationELB",
     "region": "default",
     "statistics": [ "SampleCount" ]
    },
    {
     "alias": "reports",
     "dimensions": { "LoadBalancer": "app/ellvpc/502ebe237ff21d6e" },
     "metricName": "HTTPCode_Target_4XX_Count",
     "namespace": "AWS/ApplicationELB",
     "region": "default",
     "statistics": [ "SampleCount" ]
    },
    {
     "alias": "ecs-prod-cluster-external",
     "dimensions": {
      "LoadBalancer": "app/ecs-prod-cluster-external/25bc585d87b33ce5"
     },
     "metricName": "HTTPCode_ELB_4XX_Count",
     "namespace": "AWS/ApplicationELB",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Request Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "reports",
     "dimensions": { "LoadBalancer": "app/ellvpc/502ebe237ff21d6e" },
     "metricName": "RequestCount",
     "namespace": "AWS/ApplicationELB",
     "region": "default",
     "statistics": [ "SampleCount" ]
    },
    {
     "alias": "production",
     "dimensions": { "LoadBalancer": "app/prodvpc/a2fa2fecdb6cd041" },
     "metricName": "RequestCount",
     "namespace": "AWS/ApplicationELB",
     "region": "default",
     "statistics": [ "SampleCount" ]
    },
    {
     "alias": "ecs-prod-cluster-external",
     "dimensions": {
      "LoadBalancer": "app/ecs-prod-cluster-external/25bc585d87b33ce5"
     },
     "metricName": "RequestCount",
     "namespace": "AWS/ApplicationELB",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "HTTPCode_Target_5XX_Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "production",
     "dimensions": { "LoadBalancer": "app/prodvpc/a2fa2fecdb6cd041" },
     "metricName": "HTTPCode_Target_5XX_Count",
     "namespace": "AWS/ApplicationELB",
     "region": "default",
     "statistics": [ "SampleCount" ]
    },
    {
     "alias": "reports",
     "dimensions": { "LoadBalancer": "app/ellvpc/502ebe237ff21d6e" },
     "metricName": "HTTPCode_Target_5XX_Count",
     "namespace": "AWS/ApplicationELB",
     "region": "default",
     "statistics": [ "SampleCount" ]
    }
   ]
  }
 ]
}