{
 "title": "RDS Stats",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "RDS Database Connections",
   "type": "graph",
   "gridPos": { "h": 4, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "bizomapaclbbk",
     "dimensions": { "DBInstanceIdentifier": "bizomapaclbbk" },
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "region": "default",
     "statistics": [ "Average" ]
    },
    {
     "alias": "logs",
     "dimensions": { "DBInstanceIdentifier": "logs" },
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "region": "default",
     "statistics": [ "Average" ]
    },
    {
     "alias": "reports",
     "dimensions": { "DBInstanceIdentifier": "reports" },
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "region": "default",
     "statistics": [ "Average" ]
    },
    {
     "alias": "staging-legacy",
     "dimensions": { "DBInstanceIdentifier": "staging-legacy" },
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "region": "ap-south-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "RDS FreeStorageSpace",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "bizomapaclbbk",
     "dimensions": { "DBInstanceIdentifier": "bizomapaclbbk" },
     "metricName": "FreeStorageSpace",
     "namespace": "AWS/RDS",
     "region": "default",
     "statistics": [ "Average" ]
    },
    {
     "alias": "logs",
     "dimensions": { "DBInstanceIdentifier": "logs" },
     "metricName": "FreeStorageSpace",
     "namespace": "AWS/RDS",
     "region": "default",
     "statistics": [ "Average" ]
    },
    {
     "alias": "reports",
     "dimensions": { "DBInstanceIdentifier": "reports" },
     "metricName": "FreeStorageSpace",
     "namespace": "AWS/RDS",
     "region": "default",
     "statistics": [ "Average" ]
    },
    {
     "alias": "staging-legacy",
     "dimensions": { "DBInstanceIdentifier": "staging-legacy" },
     "metricName": "FreeStorageSpace",
     "namespace": "AWS/RDS",
     "region": "ap-south-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "RDS Read IOPS",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "bizomapaclbbk",
     "dimensions": { "DBInstanceIdentifier": "bizomapaclbbk" },
     "metricName": "ReadIOPS",
     "namespace": "AWS/RDS",
     "region": "default",
     "statistics": [ "Average" ]
    },
    {
     "alias": "logs",
     "dimensions": { "DBInstanceIdentifier": "logs" },
     "metricName": "ReadIOPS",
     "namespace": "AWS/RDS",
     "region": "default",
     "statistics": [ "Average" ]
    },
    {
     "alias": "reports",
     "dimensions": { "DBInstanceIdentifier": "reports" },
     "metricName": "ReadIOPS",
     "namespace": "AWS/RDS",
     "region": "default",
     "statistics": [ "Average" ]
    },
    {
     "alias": "staging-legacy",
     "dimensions": { "DBInstanceIdentifier": "staging-legacy" },
     "metricName": "ReadIOPS",
     "namespace": "AWS/RDS",
     "region": "ap-south-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "RDS ReadThroughput",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "bizomapaclbbk",
     "dimensions": { "DBInstanceIdentifier": "bizomapaclbbk" },
     "metricName": "ReadThroughput",
     "namespace": "AWS/RDS",
     "region": "default",
     "statistics": [ "Average" ]
    },
    {
     "alias": "logs",
     "dimensions": { "DBInstanceIdentifier": "logs" },
     "metricName": "ReadThroughput",
     "namespace": "AWS/RDS",
     "region": "default",
     "statistics": [ "Average" ]
    },
    {
     "alias": "reports",
     "dimensions": { "DBInstanceIdentifier": "reports" },
     "metricName": "ReadThroughput",
     "namespace": "AWS/RDS",
     "region": "default",
     "statistics": [ "Average" ]
    },
    {
     "alias": "staging-legacy",
     "dimensions": { "DBInstanceIdentifier": "staging-legacy" },
     "metricName": "ReadThroughput",
     "namespace": "AWS/RDS",
     "region": "ap-south-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "RDS Write IOPS",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "bizomapaclbbk",
     "dimensions": { "DBInstanceIdentifier": "bizomapaclbbk" },
     "metricName": "WriteIOPS",
     "namespace": "AWS/RDS",
     "region": "default",
     "statistics": [ "Average" ]
    },
    {
     "alias": "reports",
     "dimensions": { "DBInstanceIdentifier": "reports" },
     "metricName": "WriteIOPS",
     "namespace": "AWS/RDS",
     "region": "default",
     "statistics": [ "Average" ]
    },
    {
     "alias": "logs",
     "dimensions": { "DBInstanceIdentifier": "logs" },
     "metricName": "WriteIOPS",
     "namespace": "AWS/RDS",
     "region": "default",
     "statistics": [ "Average" ]
    },
    {
     "alias": "staging-legacy",
     "dimensions": { "DBInstanceIdentifier": "staging-legacy" },
     "metricName": "WriteIOPS",
     "namespace": "AWS/RDS",
     "region": "ap-south-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "RDS WriteThroughput",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "bizomapaclbbk",
     "dimensions": { "DBInstanceIdentifier": "bizomapaclbbk" },
     "metricName": "WriteThroughput",
     "namespace": "AWS/RDS",
     "region": "default",
     "statistics": [ "Average" ]
    },
    {
     "alias": "logs",
     "dimensions": { "DBInstanceIdentifier": "logs" },
     "metricName": "WriteThroughput",
     "namespace": "AWS/RDS",
     "region": "default",
     "statistics": [ "Average" ]
    },
    {
     "alias": "reports",
     "dimensions": { "DBInstanceIdentifier": "reports" },
     "metricName": "WriteThroughput",
     "namespace": "AWS/RDS",
     "region": "default",
     "statistics": [ "Average" ]
    },
    {
     "alias": "staging-legacy",
     "dimensions": { "DBInstanceIdentifier": "staging-legacy" },
     "metricName": "WriteThroughput",
     "namespace": "AWS/RDS",
     "region": "ap-south-1",
     "statistics": [ "Average" ]
    }
   ]
  }
 ]
}