pipelines:

  branches:
    ${branch}:
      - step:
          size: 2x
          name: Deploy to "${environment}" environment
          image:
            name: 596849958460.dkr.ecr.${region}.amazonaws.com/bizom:latest
            aws:
              access-key: \$AWS_ACCESS_KEY_ID
              secret-key: \$AWS_SECRET_ACCESS_KEY
          caches:
            - maven
            - docker
          deployment: ${environment}
          services:
            - docker
          script:
            - \$(aws ecr get-login --no-include-email --region "${region}") && ops/deploy.sh "${environment}" "${environment}" "1" "\$WEBHOOK_URL"
          after-script:
             - ops/alert.sh

definitions:
  services:
    docker:
      memory: 5120
