apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: ell
  name: devel-ell
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: ell
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  name: system:aggregated-metrics-reader
rules:
- apiGroups:
  - metrics.k8s.io
  - get pods.metrics.k8s.io
  resources:
  - pods
  - nodes
  verbs:
  - get
  - list
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: ell
  name: system:devel-ell-server
rules:
- apiGroups:
  - ""
  resources:
  - nodes/metrics
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  verbs:
  - get
  - list
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: ell
  name: devel-ell-auth-reader
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: devel-ell-apiserver-authentication-reader
subjects:
- kind: ServiceAccount
  name: devel-ell
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: ell
  name: devel-ell:system:auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: devel-ell
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: ell
  name: system:devel-ell
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:devel-ell
subjects:
- kind: ServiceAccount
  name: devel-ell
  namespace: kube-system

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ell
  namespace: devel-ell
spec:
  minReplicas: 1
  maxReplicas: 2 
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ell
  targetCPUUtilizationPercentage: 50

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-logging
  namespace: aws-observability
data:
  output.conf: |
    [OUTPUT]
      Name cloudwatch_logs
      Match *
      region ap-south-1
      log_group_name eks-devel-cloudwatch
      log_stream_prefix eks-devel-cluster-
      auto_create_group true
      log_key log
