---
apiVersion: v1
kind: Service
metadata:
  name: ell
  namespace: devel-services
spec:
  type: ClusterIP
  selector:
    app: ell
  ports:
    - name: https
      protocol: TCP
      port: 8080
      targetPort: 8080

