apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: config 
  name: devel-config
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: config
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  name: system:aggregated-metrics-reader
rules:
- apiGroups:
  - metrics.k8s.io
  - get pods.metrics.k8s.io
  resources:
  - pods
  - nodes
  verbs:
  - get
  - list
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: config
  name: system:devel-config-server
rules:
- apiGroups:
  - ""
  resources:
  - nodes/metrics
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  verbs:
  - get
  - list
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: config
  name: devel-config-auth-reader
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: devel-config-apiserver-authentication-reader
subjects:
- kind: ServiceAccount
  name: devel-config
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: config
  name: devel-config:system:auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: devel-config
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: config
  name: system:devel-config
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:devel-config
subjects:
- kind: ServiceAccount
  name: devel-config
  namespace: kube-system

---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  labels:
    app: devel-config
  name: v1beta1.metrics.k8s.io
spec:
  group: metrics.k8s.io
  groupPriorityMinimum: 100
  insecureSkipTLSVerify: true
  service:
    name: devel-config
    namespace: kube-system
  version: v1beta1
  versionPriority: 100

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: config
  namespace: devel-config
spec:
  minReplicas: 1
  maxReplicas: 2 
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: config
  targetCPUUtilizationPercentage: 50

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-logging
  namespace: aws-observability
data:
  output.conf: |
    [OUTPUT]
      Name cloudwatch_logs
      Match *
      region ap-south-1
      log_group_name eks-devel-cluster-cloudwatch
      log_stream_prefix eks-devel-cluster-
      auto_create_group true
      log_key log
